/**
 * orval.config.ts is intentionally excluded from tsconfig.json and eslint.
 * It requires moduleResolution: "node" which conflicts with the app's "bundler" setting.
 * Regenerate the client with: npm run generate:api
 */

import { defineConfig } from 'orval';

export default defineConfig({
	pragmata: {
		input: {
			target: '../docs/api/openapi.yaml',
		},
		output: {
			target: './src/api/generated/services',
			client: 'react-query',
			httpClient: 'axios',
			mode: 'tags-split',
			prettier: true,
			headers: true,
			clean: true,
			override: {
				query: {
					useQuery: true,
					useMutation: true,
					useInvalidate: true,
					signal: true,
					useOperationIdAsQueryKey: false,
				},
				useDates: true,
				useNamedParameters: true,
				enumGenerationType: 'enum',
				mutator: {
					path: './src/api/generatedAPIInstance.ts',
					name: 'GeneratedAPIInstance',
				},

				jsDoc: {
					filter: (schema) => {
						const allowlist = [
							'type',
							'format',
							'maxLength',
							'minLength',
							'description',
							'minimum',
							'maximum',
							'exclusiveMinimum',
							'exclusiveMaximum',
							'pattern',
							'nullable',
							'enum',
						];
						return Object.entries(schema || {})
							.filter(([key]) => allowlist.includes(key))
							.map(([key, value]: [string, any]) => ({ key, value }))
							.sort((a, b) => a.key.length - b.key.length);
					},
				},

				components: {
					schemas: { suffix: 'DTO' },
					responses: { suffix: 'Response' },
					parameters: { suffix: 'Params' },
					requestBodies: { suffix: 'Body' },
				},

				header: (info: { title: string; version: string }): string[] => [
					`! Do not edit manually`,
					`* Auto-generated by Orval from the OpenAPI spec`,
					`* Regenerate with 'npm run generate:api'`,
					...(info.title ? [info.title] : []),
					...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
				],

				// @ts-expect-error — valid orval options not yet in the type definitions
				propertySortOrder: 'Alphabetical',
				urlEncodeParameters: true,
				aliasCombinedTypes: true,
			},
		},
	},
});
