services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.5.6
    container_name: pragmata-clickhouse
    volumes:
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse-data:/var/lib/clickhouse/
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1

  zookeeper:
    image: signoz/zookeeper:3.7.1
    container_name: pragmata-zookeeper
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD-SHELL", "curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  clickhouse-data:
  zookeeper-data:
